archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
themesDir = "themes"
baseURL = "https://dashMrl.github.io/Blog/"
languageCode = "en"
title = "小站"
theme = "hugo-nuo"


buildDrafts = false
buildExpired = false
buildFuture = false
uglyURLs = true
enableEmoji  = true
enableGitInfo = true
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
disableHugoGeneratorInject = true

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "dashMrl"
  avatar = "/img/avatar.jpg"
  seotitle = "dashMrl's Blog"
  subtitle = "~ Keep It Simple & Stupid ~"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "xinliugm@gmail.com"
  github = "dashMrl"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  weibo = "weibo_username"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = false
  changyanId = "cyt3toRiB"
  changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"

# Disqus Username
disqusShortname = "disqus_shortname"

# Copyright of your post
copyright = "207-2018 © This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Google Analytics UA number
googleAnalytics = "UA-90333409-1"


[permalinks]
  post = "/post/:year/:month/:title.html"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[frontmatter]
  date = ["date","publishDate", "lastmod"]
  lastmod = [":git" ,"lastmod", "date","publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

verbose = true
verboseLog = true