name: Generate site

on:
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    name: Build and deploy blog
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v16.x.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Setup environment
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "clsrfish@gmail.com"
          git config --global user.name "GitHub Action"
          echo $(date)
          npm install

      - name: Deploy
        run: |
          npm run clean
          npm run build
          npm run gulp
          npm run deploy
